[package]
name = "hash_mnemonics"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = "1.0"
serde_derive = "1.0"
csv = "1.3.0"
clap = { version = "4.5.20", features = ["derive"] }
sha256 = "1.5"