[package]
name = "address_filter"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = "1.0"
serde_derive = "1.0"
csv = "1.3.0"
clap = { version = "4.5.20", features = ["derive"] }
bloomfilter = "1.0.14"